### ISSUE TITLE
Left Hand Drive Content?

### ISSUE THREAD

**Issue by probablyry** [CSX8600/trafficcontrol#14]
It'd be kinda neat if there was a chance for flipping the boom gates so that they can be used on the left - this isn't just cool for AU/UK/etc players but for players from parts of the world that use double boom gates. I know it's kinda trivial but it would be super appreciated.

**Comment by CSX8600** [comment]
Assuming this was prior to the model update. Additionally, you can just place them in the opposite direction. I've seen some screenshots where people do gates on both sides of the road. Closing as won't do.
