### ISSUE TITLE
Automated Shunts crash with 1.61-1138

### ISSUE THREAD

**Issue by Turtle-star** [CSX8600/trafficcontrol#18]
Title says it all, whenever an island shunt is setup it crashes the game.

**Comment by 412pgh3** [comment]
I have the same exact issue. It appears to be a server tick loop crash. Ive had issues in the past with every version of this mod newer then 0.0.8 causing tick crashes

**Comment by CSX8600** [comment]
Ensure that you have the proper versions of Immersive Railroading for the version of Traffic Control you're using.
