### ISSUE TITLE
[Suggestion] Horizontal Traffic Light please (4 and 5 bulbs)

### ISSUE THREAD

**Issue by ExDomino** [CSX8600/trafficcontrol#19]
Hello, I would like to suggest you to add Horizontal Traffic Light, one with 4 bulbs and one with 5 bulbs.

Why 4 ? In order to reproduce this Traffic Light :
https://thumbs.dreamstime.com/z/horizontal-double-red-traffic-light-horizontal-double-red-traffic-light-against-blue-sky-background-122090156.jpg
And 5 for the Turn Left Green Signal. For those who want a Turn Left Yellow Signal, just remove one of the two Red Bulbs.

Thank you in advance.

**Comment by CSX8600** [comment]
Suggestions are housed within our Discord server (https://discord.gg/3yeea4F2Cs). Please post this there, if it's not already been suggested.
