### ISSUE TITLE
[Suggestion] Redstone signal applied to sensor trigger signal

### ISSUE THREAD

**Issue by ExDomino** [CSX8600/trafficcontrol#20]
Hello,

My idea is: if you apply a signal redstone signal to a sensor, the sensor acts like a car is hover it.
Thank you in advance.

As a bonus, I noticed that at this moment, if two cars wait on each direction without moving, the traffics light by themself cycle like real ones. So, with a redstone signal applyed on each sensors, we could reproduce this behavior in the game.

**Comment by CSX8600** [comment]
Suggestions are housed within our Discord server (https://discord.gg/3yeea4F2Cs). Please post this there, if it's not already been suggested.
