### ISSUE TITLE
Crash when pairing island shunt to relax box with tuner

### ISSUE THREAD

**Issue by xxxman360** [CSX8600/trafficcontrol#25]
It seems this is the cause of my game crashing as I've repeated the process several times. What is really bad is I can no longer go into the world after this happens as it crashes upon loading it in. Please fix this as it would be most helpful.

**Comment by xxxman360** [comment]
This the error I get:

> Description: Exception in server tick loop
> 
> java.lang.NoSuchMethodError: cam72cam.mod.math.Vec3d.internal()Lnet/minecraft/util/math/Vec3d;
> 	at com.clussmanproductions.trafficcontrol.util.ImmersiveRailroadingHelper.getNextPosition(ImmersiveRailroadingHelper.java:111)
> 	at com.clussmanproductions.trafficcontrol.scanner.Scanner.tick(Scanner.java:84)
> 	at com.clussmanproductions.trafficcontrol.event.WorldEventHandler.onTick(WorldEventHandler.java:54)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_30_WorldEventHandler_onTick_WorldTickEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
> 	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
> 	at java.lang.Thread.run(Unknown Source)

**Comment by CSX8600** [comment]
Ensure you are using the proper versions of Traffic Control and Immersive Railroading.
