### ISSUE TITLE
Make drivers for opencomputer avalable.

### ISSUE THREAD

**Issue by jcc10** [CSX8600/trafficcontrol#29]
I would absolutely love to be able to use my traffic lights with more of a granular control with something like open computers. I would love it if a API could be added with the following functions:

```
setLight([Direction], [Type], [Color], [State])
getSensor([Direction, [Type])
```

With the enum's of:
```
Directions: N/S/E/W
Types: Light, Left
Color: Red, Yellow Green
State: On/Solid, Flashing, Off
```
This would allow for fully custom traffic light control.

Relevant Doc: https://github.com/MightyPirates/OpenComputers/tree/master-MC1.12/src/main/java/li/cil/oc/api

**Comment by CSX8600** [comment]
Hah - didn't even see this before I started working on it. Done on commit f22d1ef.
