### ISSUE TITLE
Pedestrian Signals & Buttons

### ISSUE THREAD

**Issue by jcc10** [CSX8600/trafficcontrol#30]
It would be really awesome if you could add pedestrian signals to the game! Buttons would also be useful. Less useful (but up there) would be adding bike and mount settings for the buttons and lights. (Pelican crossing, Toucan crossing, and Pegasus crossing respectively.)

It would probably also require a dual signal container.

**Comment by jcc10** [comment]
Added a bit more to the original.

* Buttons (How could I forget!)
* Bike mode request (Toucan Crossing)
* Mount mode request (Pegasus crossing)

**Comment by CSX8600** [comment]
Already added pedestrian crossings and buttons. Please add your other suggestions on our Discord at https://discord.gg/3yeea4F2Cs
