### ISSUE TITLE
Texture problem with the posts and the Fureniku's Roads mod

### ISSUE THREAD

**Issue by ItsJustMiaouss** [CSX8600/trafficcontrol#52]
The texture of the block where the post is placed becomes invisible with a
[Fureniku's Roads](https://www.curseforge.com/minecraft/mc-mods/furenikusroads)'s block.

![image](https://user-images.githubusercontent.com/59478524/144920563-f29acdda-739f-4ab8-a89e-e114d4ae693e.png)

The modded block is the "Standard Tarmac Road" from Fureniku's Roads mod.
The vanilla block is a Stone Block.

**Comment by RavenholmZombie** [comment]
<img src="https://i.imgur.com/E7ZmDPA.png" width=400>

Unable to reproduce using version 1.1.6 of Fureniku's Roads.
Newer versions have been known to have culling issues, please report this issue to them.
