### ISSUE TITLE
Missing signs

### ISSUE THREAD

**Issue by TheEpicness9000** [CSX8600/trafficcontrol#53]
Many signs I added in the last update don't have mirrored counterparts. Attached are the necessary signs to complete the mirroring.
[Signs That Need Mirror Images-20211206T215006Z-001.zip](https://github.com/CSX8600/trafficcontrol/files/7663754/Signs.That.Need.Mirror.Images-20211206T215006Z-001.zip)

**Comment by CSX8600** [comment]
Opting to recommend the usage of the upcoming signpacks
