### ISSUE TITLE
[Suggestion] Traffic Light Bulbs with straight arrows

### ISSUE THREAD

**Issue by Taylo160** [CSX8600/trafficcontrol#66]
I would love to see Traffic Light Bulbs with straight arrows in Traffic control, I really like this Mod and i sometimes just cant build a crossing without Straight Arrow Traffic Ligths.

**Comment by CSX8600** [comment]
Pull request #60 adds these, but the requester needs to make the required changes before the next release cut otherwise they won't be added. TBD...

**Comment by CSX8600** [comment]
Added as of 1.0.0
