### ISSUE TITLE
[Suggestion] Crossing Relay Boxes output Redstone and No gate lights option

### ISSUE THREAD

**Issue by Taylo160** [CSX8600/trafficcontrol#71]
It would be very useful if Crossing Relay Boxes with automatic activation (Shunts) could output a redstone signal directly or via a comparator when activated.

for example:
if i want to build an pedestrian crossing with a flashing „stop“ bulb in a 1 bulb frame i would need a redstone signal from the Relay box to activate a traffic light control box 

It would also be very cool if there was an option in addition to 1 light and 3lights to turn of the gate lights.

for example:
here in germany where i live we dont have gate lights so if i want to build such a railroad crossing in TC i would have to use a version wich doesnt have gate lights.

**Comment by KreativeKngYT** [comment]
yes please, I could really use this feature

**Comment by CSX8600** [comment]
The chief problem is that crossing relay boxes _accept_ power, so making it also emit power would be weird, I think?

Gate lights can be disabled by simply setting a Light Start Offset to a higher number than the gate's length. For example, if you had a gate length of 5 blocks, set your Light Start Offset to 6 and the gate lights will disappear.

**Comment by KreativeKngYT** [comment]
Maybe make it so the front accepts Redstone and the back outputs it.

**Comment by CSX8600** [comment]
Let's move this to the suggestions channel in Discord so that ideas on how to make this work from others can be more easily shared. Closing.
