### ISSUE TITLE
[IMPORTANT] Text Render Clipping on Signs

### ISSUE THREAD

**Issue by RavenholmZombie** [CSX8600/trafficcontrol#72]
![image](https://user-images.githubusercontent.com/1634865/235230478-564e0ad4-1bca-4e9b-919e-f907a615c5d7.png)

Text on signs will begin to have rendering issues when the player is just a few blocks away.

**Comment by CSX8600** [comment]
Textures on Type 3 Barriers are also z-fighting

**Comment by RavenholmZombie** [comment]
![image](https://user-images.githubusercontent.com/1634865/235355444-8f04e0ca-a01c-46ea-a970-0a069e7b5574.png)
