### ISSUE TITLE
Game crashes when placing traffic light frame

### ISSUE THREAD

**Issue by Dimentive** [CSX8600/trafficcontrol#8]
When I placed a traffic light frame on the ground, my game crashed.

* **Crash log:** https://pastebin.com/raw/g2QSPv1e
* **Full mod list:** https://pastebin.com/raw/txXgutsS

Judging from the crash log, this crash was caused by a bad interaction between McJty’s [The One Probe](https://www.curseforge.com/minecraft/mc-mods/the-one-probe) mod and Traffic Control. The One Probe is a mod that displays a little box with information about the block that you’re looking at. It’s very similar to the mods [Waila](https://www.curseforge.com/minecraft/mc-mods/waila) and [Hwyla](https://www.curseforge.com/minecraft/mc-mods/hwyla).

It looks like this crash might be similar, but not identical to, #7, which was caused by a bad interaction between _Waila_ and The One Probe. However, the two crash logs are quite a bit different too, so I’m not sure if it’s the same issue. I also don’t know whether this is a problem on Traffic Control’s end or on The One Probe’s end.

When my game loaded again after the crash, the traffic light frame was there and didn’t crash my game again.

![2020-01-10_05 24 41](https://user-images.githubusercontent.com/34230933/72125621-8d188b00-3369-11ea-841b-262a37a0c427.png)

#### Versions
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2847 (latest for 1.12.2)
* **Traffic Control:** 0.1.0 (latest)

**Comment by CSX8600** [comment]
This is definitely the same issue as #7 .  The fix has been programmed and is waiting for testing.  Expect it tonight sometime

**Comment by Dimentive** [comment]
Nice!
