### ISSUE TITLE
Question about using textures in my mod

### ISSUE THREAD

**Issue by Emil352** [CSX8600/trafficcontrol#80]
Good evening
I have not found a better way to contact you
I have a question may I use your mod textures in my mod ?

**Comment by CSX8600** [comment]
This mod is MIT license, so you can use any or all of the code at will. Just be respectful about it, please :)

I haven't done development on this for a long time as I'm currently working on another project. Still, a Discord server does exist: discord.gg/3yeea4F2Cs
