### ISSUE TITLE
Big Screen Street Sign Bug

### ISSUE THREAD

**Issue by CreatingCalifornia** [CSX8600/trafficcontrol#92]
On large screens, when editing a street sign, you’re not able to see all of the color options. this does get pretty annoying, especially when the only way you could do it is by minimizing the app and trying to make it small enough to change it.
![Uploading image.jpg…]()

**Comment by CreatingCalifornia** [comment]
![Uploading image.jpg…]()

**Comment by CSX8600** [comment]
Change gui scale to a smaller option to resolve this issue.

**Comment by CreatingCalifornia** [comment]
How would you do that?

**Comment by CSX8600** [comment]
This is for 1.17, but same area and concept

https://youtu.be/w9e9jBmFzC4?si=uh9gQ5Epd6HRsAF9
