### ISSUE TITLE
All Sign Texture Spontaneously Disappearing 

### ISSUE THREAD

**Issue by CreatingCalifornia** [CSX8600/trafficcontrol#95]
I was flying around my server, all my sign textures randomly disappeared, but still left the frame for the signs. Even placing down a new sign, even has the default new sign texture missing. The only signs the stayed are the ones from RTC. I did indeed try F3 + T but still had no luck with solving the problem.
![IMG_4026](https://github.com/CSX8600/trafficcontrol/assets/156473479/827512fd-9399-4050-8e6f-45df28e23ab7)
![IMG_4027](https://github.com/CSX8600/trafficcontrol/assets/156473479/022112cf-8544-46f2-90a8-fab33426fbfc)

**Comment by GamearooCodes** [comment]
question did you have charas signpack v9 installed and not update to the latest v9's??

if not can you provide more info on what signpacks you used and the last thing you did b4 this happened

**Comment by CreatingCalifornia** [comment]
No, I updated it to v9.1

Plus it’s not just signpack signs, it’s all signs

**Comment by GamearooCodes** [comment]
Have you tried reinstalling traffic control? Also what steps did you do the lead to this problem so I can try to reproduce this issue

**Comment by CreatingCalifornia** [comment]
I was just flying around my mc world, until I noticed my signs were starting to disappear

**Comment by GamearooCodes** [comment]
I'm asking like did you change anything add anything new etc..

**Comment by CreatingCalifornia** [comment]
No, not at all. A did add stuff couple days ago. The only problems I had before with signs are the gray text, never them disappearing like this.

**Comment by GamearooCodes** [comment]
Mind sending me a dm on discord so I can further look into this and get more info so I can track this and see a possible fix??

**Comment by CreatingCalifornia** [comment]
Sure. Np

**Comment by GamearooCodes** [comment]
Cool my username is gamearoo u can also find me in the csx discord
